server {
    listen 80;

    location / {
        proxy_pass         http://app:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Cf-Access-Authenticated-User-Email $http_cf_access_authenticated_user_email;
        proxy_read_timeout 30s;
    }
}
